[project]
name = "queryrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aguimmanuel", email = "aguimmanuel7@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
queryrag = "queryrag:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
